project: ${GOOGLE_CLOUD_PROJECT}
location: ${GOOGLE_CLOUD_LOCATION}
use_vertexai: ${GOOGLE_GENAI_USE_VERTEXAI}

dataset:
  images_dir: "data/raw/img"
  annotations_file: "data/raw/annotations.csv"
  examples_dir: "data/sample"

# Default question for all prompts
prompt_question: "This rebus puzzle is an Idiom which may contain text, figures, and other logical clues to represent the Idiom. Can you figure out what this Idiom is? Output your final answer in three braces, like {{{this}}}."

logging:
  level: "INFO"
  dir: "logs"

# Default prompt styles
prompt_styles:
  - zero_shot
  - fewshot2_cot
  - fewshot3_cot
  - fewshot2_nocot
  - fewshot3_nocot

request:
  batch_size: 4
  timeout_seconds: 60

# Evaluation settings
evaluation:
  use_extraction: true
  use_f1: true
  normalize_for_comparison: true